In [1]:
import os
import numpy as np
import pandas as pd
from scipy.signal import hilbert
from scipy.signal import butter, lfilter, freqz
from scipy.signal import find_peaks
import matplotlib.pyplot as plt
import librosa
import librosa.display

In [34]:
def get_signal(Path):
    envs = []
    files = os.listdir(Path)
    for f in files:
        if f.endswith('.wav'):
            #print(f)
            signal, sr = librosa.load(Path+'\\'+f)
            #t = np.arange(signal.size)/sr
            #print(t)
            #librosa.display.waveshow(signal, sr=sr)
            #print(sr, signal)
            analytic_signal = hilbert(signal)
            amplitude_envelope = np.abs(analytic_signal)
            envs.append(amplitude_envelope)
    return envs

In [35]:
def butter_lowpass_filter(data, cutoff, fs, order=5):
    all_peaks = []
    #print(cutoff)
    b, a = butter(5, 10, 'low', analog=False, fs=22050)
    y = lfilter(b, a, data)
    #print(y)
    peaks, _ = find_peaks(y, height=0.01)
    #print(peaks)
    #plt.plot(y)
    #plt.plot(peaks, y[peaks], "x")
    #plt.plot(np.zeros_like(y), "--", color="gray")
    #plt.show()
    all_peaks.append(len(peaks))
    return all_peaks

In [162]:
C = get_signal('C:\\Users\\varya\\master_thesis\\out_C1_babble')

In [163]:
len(C)

158

In [164]:
times = []
fin_nested = []
for env in C:
    res = butter_lowpass_filter(env, 10, 220050, order=5)
    fin_nested.append(res)
    time = len(env)/22050
    times.append(time)
#print(times)
fin = [item for sublist in fin_nested for item in sublist]
print(fin)

[4, 11, 17, 8, 10, 7, 16, 5, 12, 28, 10, 10, 10, 21, 18, 15, 15, 15, 23, 19, 15, 11, 11, 17, 13, 1, 27, 2, 3, 5, 19, 26, 7, 19, 21, 32, 21, 11, 34, 25, 27, 15, 14, 8, 13, 13, 5, 9, 5, 31, 13, 21, 6, 19, 18, 19, 11, 16, 10, 18, 14, 8, 33, 16, 11, 8, 7, 13, 19, 17, 6, 16, 19, 5, 18, 33, 8, 28, 8, 4, 17, 5, 19, 3, 12, 18, 33, 20, 13, 15, 21, 15, 6, 16, 20, 6, 16, 12, 12, 20, 8, 21, 20, 17, 8, 15, 3, 19, 22, 8, 12, 33, 10, 20, 24, 5, 8, 27, 8, 12, 26, 14, 8, 21, 8, 4, 6, 27, 4, 18, 8, 10, 11, 18, 16, 7, 32, 8, 6, 18, 10, 16, 14, 15, 25, 8, 8, 10, 27, 8, 5, 6, 14, 9, 17, 21, 17, 18]

In [165]:
rates = [a/b for a, b in zip(fin, times)]
rates
#np.mean(rates)

[7.638347622759159,
 5.868618436970723,
 4.313281016270453,
 6.452084857351866,
 5.346361806852072,
 5.465458022024716,
 5.9699472045485305,
 5.431837217322757,
 5.880130669570435,
 5.857907320960947,
 6.1044821571938765,
 6.023602688083921,
 7.9998548779160465,
 5.947824076452756,
 5.624920281742038,
 5.81405568837013,
 5.281858831044395,
 5.595499915411944,
 6.609884524150875,
 5.221341509010693,
 7.69203934975232,
 5.585878126295427,
 4.9784482758620685,
 5.864178217202214,
 6.219083571986462,
 1.613493341138592,
 5.018798893984354,
 3.949843260188088,
 4.506437768240343,
 6.942695214105794,
 5.810357261733052,
 5.590661751799193,
 6.978479066823402,
 5.740141945030554,
 6.069921086437879,
 6.153202176642948,
 6.089397964282896,
 5.524553571428571,
 5.861656463303075,
 5.766334023724346,
 6.193304760319574,
 5.419732249659987,
 6.389981370316705,
 7.402744554954047,
 6.746293245469522,
 7.262293835980846,
 6.30432296431839,
 7.570382238498512,
 7.693112832321541,
 6.980983700314556,
 4.709680599369086,
 5.660619544754407,
 5.218111540585312,
 6.411845730027548,
 6.763918948857342,
 5.809873803910691,
 4.602379461490294,
 5.674397658185093,
 6.294784321562134,
 6.077914918379223,
 6.085756530310498,
 6.664651654828472,
 6.309614650896604,
 7.047542948461845,
 6.58709467166368,
 5.340599455040872,
 3.6661837010997362,
 5.416564312843673,
 7.068380827048641,
 4.06716215483101,
 6.313528990694345,
 6.323940632394064,
 6.565173786316482,
 6.559376487386958,
 5.389294734269343,
 5.250265164907319,
 7.061366638645371,
 5.263157894736842,
 5.753049377079121,
 6.588481362515873,
 6.61367726454709,
 9.502671953111532,
 6.0802867799660385,
 4.599819205896669,
 5.658803652772728,
 5.767889321629948,
 6.179775280898877,
 5.55513566623838,
 5.563750703596591,
 5.5326017864909165,
 6.344019728729963,
 5.995866794771858,
 5.60450732864526,
 5.773762765121759,
 6.329477279903551,
 6.593570894592574,
 5.386670738224292,
 6.002041510717931,
 4.9917935367026995,
 5.037927252787425,
 6.4568081991215225,
 5.04719654691315,
 6.4932196651795575,
 7.908394691871136,
 6.068320203653377,
 5.554715840386941,
 6.123865950749861,
 5.847745069301956,
 7.030027244797403,
 6.0145248729926015,
 6.282200432109025,
 6.610973316252828,
 5.495190151024274,
 5.346102557885804,
 6.045512703344909,
 5.3983254174215345,
 5.715396578538103,
 6.330480089318943,
 5.2631578947368425,
 6.187736775641925,
 4.9334377447141735,
 5.9802402169701665,
 5.225737646640597,
 5.264384542798349,
 5.80129575426711,
 6.450669202077086,
 6.124149423691153,
 5.673728450124368,
 4.4102205110255515,
 6.741515779461222,
 5.884315164453932,
 8.399040109701748,
 7.140544041450776,
 6.765417788838509,
 6.451494925482308,
 5.117366222399045,
 6.062376492825844,
 4.737478179132537,
 5.82562747688243,
 5.439743431602319,
 5.373985523141039,
 5.419604590073275,
 6.360751669001896,
 6.140806891814114,
 6.2184144030322175,
 6.438191174860396,
 5.841059602649007,
 8.927486942791207,
 6.863061546797007,
 6.558108409547179,
 4.274747004769106,
 5.5532236400268635,
 5.447422753180752,
 5.842951360263808,
 7.531645569620253,
 5.113862260900296,
 5.839967594684282,
 6.378875299336237]

In [166]:
df = pd.DataFrame({"Noise": "Babble", "Rate": rates})
df.insert(0, "Talker", "C1")
#df
df.to_csv('C1_babble_rates.csv', encoding='utf-8', index=False)

In [167]:
df

    Talker   Noise      Rate
0       C1  Babble  7.638348
1       C1  Babble  5.868618
2       C1  Babble  4.313281
3       C1  Babble  6.452085
4       C1  Babble  5.346362
..     ...     ...       ...
153     C1  Babble  5.842951
154     C1  Babble  7.531646
155     C1  Babble  5.113862
156     C1  Babble  5.839968
157     C1  Babble  6.378875

[158 rows x 3 columns]